model:
  qformer_config:
    add_cross_attn: true
    num_hidden_layers: 2
    hidden_size: 256
    layer_norm_eps: 1e-12
    hidden_dropout_prob: 0.1
    num_attention_heads: 16
    encoder_hidden_size: 1024
    attention_probs_dropout_prob: 0.1
    max_position_embeddings: 512
    chunk_size_feed_forward: 0
    num_query_tokens: 50
    with_bg_query: true
    num_bg_query_tokens: 50
    intermediate_size: 3072
    hidden_act: "gelu"
  sam_config:
    type: vit_h
    ckpt: "ckpts/sam/sam_vit_h_4b8939.pth"
    train_mask_decoder: false
  dinov2_config:
    type: "ckpts/dinov2/large"
  with_simple_fpn: true
  multi_scale_fusion: 'concat'
  feat_interpolate: false
  with_mask: true
  with_mask_pooling: true
  no_augment: false
  with_mlp_reweight: false
loss:
  dice: 5
  ce: 20
  # focal: 10
  # iou: 10